/**
 * Mock request handlers.
 *
 * Addressed by the same path strings the real API uses, so the transport swap
 * is genuinely one line. Business rules are enforced here rather than in the
 * UI — the gate, the draft cap and the review chain are re-checked on every
 * mutation exactly as a server would, so the UI cannot drift into permitting
 * something the rules forbid.
 */

import { ApiError } from "@/lib/api/errors";
import type { ApiRequest, ApiResponse, Transport } from "@/lib/api/transport";
import { classify, delayFor } from "@/lib/api/mock/latency";
import { getScenarios } from "@/lib/api/mock/scenarios";
import { newId, nowIso, store, type Database } from "@/lib/api/mock/store";
import { seedDatabase } from "@/lib/api/mock/seed";
import { canSubmit, draftBudget, ownerForStatus } from "@/lib/domain/deliverables";
import { applyDecision, validateDecision } from "@/lib/domain/review";
import { allowedTransitions } from "@/lib/domain/participation";
import { SLA_DEFAULT_HOURS, startsClock } from "@/lib/domain/sla";
import { addHours } from "@/lib/format/datetime";
import type {
  CampaignAssignment,
  Deliverable,
  DeliverableStatus,
  Id,
  Review,
  ReviewStage,
  SubmissionVersion,
  Task,
  TaskType,
} from "@/lib/types";

store.registerSeeder(seedDatabase);

/** Replayed responses for repeated idempotency keys. */
const idempotencyCache = new Map<string, unknown>();

/* ── routing ────────────────────────────────────────────────────────── */

type Handler = (ctx: HandlerContext) => unknown;

interface HandlerContext {
  db: Database;
  params: Record<string, string>;
  query: Record<string, string | number | boolean | undefined>;
  body: Record<string, unknown>;
}

interface Route {
  method: string;
  pattern: RegExp;
  keys: string[];
  handler: Handler;
  mutates: boolean;
}

const routes: Route[] = [];

function route(method: string, template: string, handler: Handler) {
  const keys: string[] = [];
  const pattern = new RegExp(
    "^" +
      template.replace(/:([A-Za-z_]+)/g, (_, key: string) => {
        keys.push(key);
        return "([^/]+)";
      }) +
      "$",
  );
  routes.push({ method, pattern, keys, handler, mutates: method !== "GET" });
}

/* ── helpers ────────────────────────────────────────────────────────── */

function must<T>(value: T | undefined | null, label: string): T {
  if (value === undefined || value === null) {
    // 404, never 403: a 403 confirms the record exists, which leaks the
    // existence of other brands' campaigns to a competitor's reviewer.
    throw new ApiError("not_found", `${label} not found`);
  }
  return value;
}

function currentUserId(db: Database): Id {
  return must(db.session.userId, "Session");
}

function deliverableOf(db: Database, id: Id): Deliverable {
  return must(
    db.deliverables.find((d) => d.id === id),
    "Deliverable",
  );
}

function versionsOf(db: Database, deliverableId: Id): SubmissionVersion[] {
  return db.submissionVersions
    .filter((v) => v.deliverable_id === deliverableId)
    .sort((a, b) => a.version_no - b.version_no);
}

function blockerOf(db: Database, d: Deliverable): Deliverable | null {
  return d.blocked_by_deliverable_id
    ? db.deliverables.find((x) => x.id === d.blocked_by_deliverable_id) ?? null
    : null;
}

function campaignForDeliverable(db: Database, d: Deliverable) {
  const assignment = must(
    db.assignments.find((a) => a.id === d.assignment_id),
    "Assignment",
  );
  const campaign = must(
    db.campaigns.find((c) => c.id === assignment.campaign_id),
    "Campaign",
  );
  return { assignment, campaign };
}

function setOwner(d: Deliverable, status: DeliverableStatus, userId: Id | null) {
  d.status = status;
  d.current_owner_kind = ownerForStatus(status);
  d.current_owner_id = d.current_owner_kind === "creator" ? userId : null;
  d.owner_since = nowIso();
}

function audit(
  db: Database,
  action: string,
  entityType: string,
  entityId: Id,
  reason: string | null = null,
) {
  db.auditLog.unshift({
    id: newId("aud"),
    actor_id: db.session.userId ?? "system",
    impersonator_id: null,
    action,
    entity_type: entityType,
    entity_id: entityId,
    before_ref: null,
    after_ref: null,
    reason,
    at: nowIso(),
    ip: null,
    user_agent: null,
  });
}

function notify(
  db: Database,
  userId: Id,
  type: Database["notifications"][number]["type"],
  title: string,
  body: string,
  deepLink: string,
) {
  db.notifications.unshift({
    id: newId("ntf"),
    user_id: userId,
    type,
    title,
    body,
    channel: "in_app",
    deep_link: deepLink,
    delivered_at: nowIso(),
    read_at: null,
  });
}

/**
 * F-TASK-03: tasks are generated by workflow transitions, never by hand.
 * Every transition that hands ownership to a creator opens a task; every
 * transition that takes it away closes one.
 */
function openTask(
  db: Database,
  userId: Id,
  type: TaskType,
  opts: {
    campaignId: Id | null;
    deliverableId: Id | null;
    dueAt: string | null;
    action: string;
    deepLink: string;
  },
) {
  const task: Task = {
    id: newId("tsk"),
    user_id: userId,
    type,
    campaign_id: opts.campaignId,
    deliverable_id: opts.deliverableId,
    status: "open",
    due_at: opts.dueAt,
    action_required: opts.action,
    deep_link: opts.deepLink,
    created_at: nowIso(),
    closed_at: null,
    closed_reason: null,
  };
  db.tasks.push(task);
  return task;
}

function closeTasksFor(db: Database, deliverableId: Id, reason: string) {
  for (const t of db.tasks) {
    if (t.deliverable_id === deliverableId && t.status === "open") {
      t.status = "completed";
      t.closed_at = nowIso();
      t.closed_reason = reason;
    }
  }
}

function startSlaClock(
  db: Database,
  deliverable: Deliverable,
  versionId: Id,
  stage: "puzzle_media" | "brand",
) {
  const hours = SLA_DEFAULT_HOURS[deliverable.type];
  db.slaClocks.push({
    id: newId("sla"),
    deliverable_id: deliverable.id,
    submission_version_id: versionId,
    stage,
    started_at: nowIso(),
    due_at: addHours(nowIso(), hours),
    paused_at: null,
    elapsed_seconds: 0,
    breached_at: null,
    mode: "calendar_hours",
  });
}

function pauseSlaClocks(db: Database, deliverableId: Id) {
  for (const c of db.slaClocks) {
    if (c.deliverable_id === deliverableId && !c.paused_at) c.paused_at = nowIso();
  }
}

/* ── auth ───────────────────────────────────────────────────────────── */

const otpStore = new Map<string, { code: string; expiresAt: number; attempts: number }>();

route("POST", "/auth/otp/request", ({ body }) => {
  const phone = String(body.phone ?? "");
  if (!/^\+91[6-9]\d{9}$/.test(phone)) {
    throw new ApiError("validation", "Enter a valid Indian mobile number.", {
      fields: { phone: "Enter a 10-digit mobile number starting 6, 7, 8 or 9." },
    });
  }
  // F-IAM-01: 6 digits, 5-minute expiry, single use.
  otpStore.set(phone, { code: "123456", expiresAt: Date.now() + 5 * 60_000, attempts: 0 });
  return { sent: true, expiresInSeconds: 300, resendAfterSeconds: 30, hint: "123456" };
});

route("POST", "/auth/otp/verify", ({ db, body }) => {
  const phone = String(body.phone ?? "");
  const code = String(body.code ?? "");
  const record = otpStore.get(phone);

  if (!record || Date.now() > record.expiresAt) {
    throw new ApiError("validation", "That code has expired. Request a new one.", {
      fields: { code: "Expired. Request a new code." },
    });
  }
  record.attempts += 1;
  if (record.attempts > 5) {
    throw new ApiError("rate_limit", "Too many attempts. Try again in 15 minutes.");
  }
  if (code !== record.code) {
    throw new ApiError("validation", "That code is not right.", {
      fields: { code: "Incorrect code. Check and try again." },
    });
  }

  otpStore.delete(phone);
  const user =
    db.users.find((u) => u.phone === phone) ??
    db.users.find((u) => u.id === "usr_creator")!;

  // F-IAM-06: suspended and rejected users cannot authenticate, and the
  // response does not distinguish which.
  if (user.status === "suspended" || user.status === "rejected") {
    throw new ApiError("forbidden", "This account cannot sign in. Contact Puzzle Media.");
  }

  db.session.userId = user.id;
  user.last_active_at = nowIso();
  const profile = db.creatorProfiles.find((p) => p.user_id === user.id);

  return {
    user,
    needsOnboarding: user.role === "creator" && !profile?.submitted_at,
  };
});

/**
 * Email and password sign-in.
 *
 * The backend schema puts email and password on Django's `auth_user`, with
 * `creator` hanging off it one-to-one. This mirrors that: the credential is
 * checked against the user record, and the creator profile is only consulted
 * afterwards to decide where to send them.
 *
 * Demo passwords live in the seed rather than being hashed, because there is
 * no server here to hash against. When the real backend lands this handler
 * is deleted wholesale, not ported.
 */
route("POST", "/auth/password/login", ({ db, body }) => {
  const email = String(body.email ?? "").trim().toLowerCase();
  const password = String(body.password ?? "");

  const fields: Record<string, string> = {};
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    fields.email = "Enter the email address you signed up with.";
  }
  if (password.length < 8) {
    fields.password = "Passwords are at least 8 characters.";
  }
  if (Object.keys(fields).length > 0) {
    throw new ApiError("validation", "Check your details.", { fields });
  }

  const user = db.users.find((u) => (u.email ?? "").toLowerCase() === email);

  // Same message whether the email is unknown or the password is wrong, so
  // the form cannot be used to discover which addresses have accounts.
  const WRONG = "That email and password do not match.";
  if (!user || (db.credentials[user.id] ?? null) !== password) {
    throw new ApiError("validation", WRONG, {
      fields: { password: WRONG },
    });
  }

  if (user.status === "suspended" || user.status === "rejected") {
    throw new ApiError("forbidden", "This account cannot sign in. Contact Puzzle Media.");
  }

  db.session.userId = user.id;
  user.last_active_at = nowIso();
  const profile = db.creatorProfiles.find((p) => p.user_id === user.id);

  return {
    user,
    needsOnboarding: user.role === "creator" && !profile?.submitted_at,
  };
});

/**
 * Password reset is stubbed deliberately. It always reports success, because
 * telling someone "no account with that email" is the same account-discovery
 * leak the login handler above avoids.
 */
route("POST", "/auth/password/forgot", ({ body }) => {
  const email = String(body.email ?? "").trim().toLowerCase();
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    throw new ApiError("validation", "Enter a valid email address.", {
      fields: { email: "Enter a valid email address." },
    });
  }
  return { sent: true };
});

route("POST", "/auth/logout", ({ db }) => {
  db.session.userId = null;
  return { ok: true };
});

/** Dev-only: switch role without a real login, so all three portals are walkable. */
route("POST", "/auth/switch-user", ({ db, body }) => {
  const userId = String(body.userId ?? "");
  must(
    db.users.find((u) => u.id === userId),
    "User",
  );
  db.session.userId = userId;
  return { ok: true };
});

/* ── me ─────────────────────────────────────────────────────────────── */

route("GET", "/me", ({ db }) => {
  const userId = db.session.userId;
  if (!userId) throw new ApiError("forbidden", "Not signed in");

  const user = must(
    db.users.find((u) => u.id === userId),
    "User",
  );
  const profile = db.creatorProfiles.find((p) => p.user_id === userId) ?? null;
  const socials = profile
    ? db.socialAccounts.filter((s) => s.creator_id === profile.id)
    : [];
  const consents = db.consents.filter((c) => c.user_id === userId);

  return { user, profile, socialAccounts: socials, consents };
});

route("PATCH", "/me/profile", ({ db, body }) => {
  const userId = currentUserId(db);
  // Auto-save writes the draft, not the record: nothing is committed to the
  // profile until the creator submits it for review.
  db.profileDrafts[userId] = {
    step: String(body.step ?? ""),
    values: (body.values ?? {}) as Record<string, unknown>,
    savedAt: nowIso(),
  };
  return { savedAt: db.profileDrafts[userId].savedAt };
});

route("GET", "/me/profile/draft", ({ db }) => {
  const userId = currentUserId(db);
  return db.profileDrafts[userId] ?? null;
});

route("POST", "/me/profile/submit", ({ db }) => {
  const userId = currentUserId(db);
  const draft = db.profileDrafts[userId];
  const profile = db.creatorProfiles.find((p) => p.user_id === userId);

  if (!profile) throw new ApiError("not_found", "Profile not found");

  Object.assign(profile, draft?.values ?? {});
  profile.submitted_at = nowIso();
  profile.verification_status = "pending_review";
  audit(db, "profile.submitted", "creator_profile", profile.id);

  return profile;
});

/* ── campaigns ──────────────────────────────────────────────────────── */

route("GET", "/campaigns", ({ db }) => {
  const userId = currentUserId(db);
  const profile = db.creatorProfiles.find((p) => p.user_id === userId);
  if (!profile) return { items: [], nextCursor: null };

  const assignments = db.assignments.filter((a) => a.creator_id === userId);
  const items = assignments.map((assignment) => {
    const campaign = db.campaigns.find((c) => c.id === assignment.campaign_id)!;
    const brand = db.brands.find((b) => b.id === campaign.brand_id)!;
    const deliverables = db.deliverables.filter((d) => d.assignment_id === assignment.id);
    return { assignment, campaign, brand, deliverables };
  });

  return { items, nextCursor: null };
});

route("GET", "/campaigns/:id", ({ db, params }) => {
  const campaign = must(
    db.campaigns.find((c) => c.id === params.id),
    "Campaign",
  );
  const brand = must(
    db.brands.find((b) => b.id === campaign.brand_id),
    "Brand",
  );
  const userId = currentUserId(db);
  const assignment =
    db.assignments.find((a) => a.campaign_id === campaign.id && a.creator_id === userId) ??
    null;
  const deliverables = assignment
    ? db.deliverables.filter((d) => d.assignment_id === assignment.id)
    : [];
  const brief = db.briefVersions
    .filter((b) => b.campaign_id === campaign.id)
    .sort((a, b) => b.version - a.version)[0];

  return { campaign, brand, assignment, deliverables, brief };
});

/* ── participation ──────────────────────────────────────────────────── */

function transitionAssignment(
  db: Database,
  assignment: CampaignAssignment,
  to: CampaignAssignment["participation_status"],
  reason: string | null,
) {
  const campaign = must(
    db.campaigns.find((c) => c.id === assignment.campaign_id),
    "Campaign",
  );
  const allowed = allowedTransitions(
    campaign.participation_mode,
    assignment.participation_status,
  );
  if (!allowed.some((t) => t.to === to)) {
    throw new ApiError(
      "conflict",
      `Cannot move from ${assignment.participation_status} to ${to}.`,
    );
  }
  assignment.participation_status = to;
  audit(db, `assignment.${to}`, "campaign_assignment", assignment.id, reason);
}

route("POST", "/assignments/:id/accept", ({ db, params }) => {
  const userId = currentUserId(db);
  const assignment = must(
    db.assignments.find((a) => a.id === params.id),
    "Assignment",
  );

  // An expired invitation cannot be accepted after the fact.
  if (assignment.participation_status === "expired") {
    throw new ApiError("conflict", "This invitation has expired.");
  }

  transitionAssignment(db, assignment, "accepted", null);
  assignment.accepted_at = nowIso();
  transitionAssignment(db, assignment, "active", null);

  // Deadlines resolve at acceptance, and the first task opens.
  const deliverables = db.deliverables.filter((d) => d.assignment_id === assignment.id);
  const campaign = db.campaigns.find((c) => c.id === assignment.campaign_id)!;
  const script = deliverables.find((d) => d.type === "script");

  for (const t of db.tasks) {
    if (t.campaign_id === assignment.campaign_id && t.type === "accept_invitation") {
      t.status = "completed";
      t.closed_at = nowIso();
      t.closed_reason = "Accepted";
    }
  }

  if (script) {
    setOwner(script, "not_started", userId);
    openTask(db, userId, "submit_script", {
      campaignId: campaign.id,
      deliverableId: script.id,
      dueAt: script.due_at,
      action: `Submit your script for ${campaign.name}`,
      deepLink: `/deliverables/${script.id}`,
    });
  }

  return assignment;
});

route("POST", "/assignments/:id/decline", ({ db, params, body }) => {
  const assignment = must(
    db.assignments.find((a) => a.id === params.id),
    "Assignment",
  );
  transitionAssignment(db, assignment, "declined", String(body.reason ?? "") || null);

  for (const t of db.tasks) {
    if (t.campaign_id === assignment.campaign_id && t.status === "open") {
      t.status = "cancelled";
      t.closed_at = nowIso();
      t.closed_reason = "Declined";
    }
  }
  return assignment;
});

route("POST", "/assignments/:id/withdraw", ({ db, params, body }) => {
  const assignment = must(
    db.assignments.find((a) => a.id === params.id),
    "Assignment",
  );
  const reason = String(body.reason ?? "");
  if (reason.trim().length < 5) {
    throw new ApiError("validation", "Tell Puzzle Media why you are withdrawing.", {
      fields: { reason: "Give a short reason." },
    });
  }

  transitionAssignment(db, assignment, "withdrawn", reason);
  assignment.withdrawn_at = nowIso();
  assignment.withdrawn_reason = reason;

  for (const t of db.tasks) {
    if (t.campaign_id === assignment.campaign_id && t.status === "open") {
      t.status = "cancelled";
      t.closed_at = nowIso();
      t.closed_reason = "Withdrew";
    }
  }
  return assignment;
});

/* ── deliverables and submissions ───────────────────────────────────── */

route("GET", "/deliverables/:id", ({ db, params }) => {
  const deliverable = deliverableOf(db, params.id);
  const { assignment, campaign } = campaignForDeliverable(db, deliverable);
  const brand = must(
    db.brands.find((b) => b.id === campaign.brand_id),
    "Brand",
  );
  const versions = versionsOf(db, deliverable.id);
  const versionIds = new Set(versions.map((v) => v.id));
  const reviews = db.reviews
    .filter((r) => versionIds.has(r.submission_version_id))
    .sort((a, b) => a.decided_at.localeCompare(b.decided_at));
  const clocks = db.slaClocks.filter((c) => c.deliverable_id === deliverable.id);
  const blocker = blockerOf(db, deliverable);
  const brief = db.briefVersions
    .filter((b) => b.campaign_id === campaign.id)
    .sort((a, b) => b.version - a.version)[0];
  const livePost = db.livePosts.find((l) => l.deliverable_id === deliverable.id) ?? null;

  return {
    deliverable,
    assignment,
    campaign,
    brand,
    brief,
    versions,
    reviews,
    slaClocks: clocks,
    blocker,
    livePost,
    budget: draftBudget(deliverable, versions),
  };
});

route("POST", "/deliverables/:id/submissions", ({ db, params, body }) => {
  const userId = currentUserId(db);
  const deliverable = deliverableOf(db, params.id);
  const versions = versionsOf(db, deliverable.id);
  const blocker = blockerOf(db, deliverable);

  // Re-checked server-side. The gate and the cap are not UI conveniences.
  const eligibility = canSubmit(deliverable, versions, blocker);
  if (!eligibility.canSubmit) {
    throw new ApiError("conflict", eligibility.reason ?? "Cannot submit right now.");
  }

  const content = body.content == null ? null : String(body.content);
  const externalLink = body.externalLink == null ? null : String(body.externalLink);
  const fileRefs = (body.fileRefs ?? []) as SubmissionVersion["file_refs"];

  if (deliverable.type === "script" && (!content || content.trim().length < 20)) {
    throw new ApiError("validation", "Write your script before submitting.", {
      fields: { content: "Scripts need at least 20 characters." },
    });
  }
  if (deliverable.type === "video" && fileRefs.length === 0 && !externalLink) {
    throw new ApiError("validation", "Attach a video or paste a preview link.", {
      fields: { file: "Upload a video file or add an approved preview link." },
    });
  }

  const scanStatus = getScenarios().infectedFile ? "infected" : "clean";
  const version: SubmissionVersion = {
    id: newId("sub"),
    deliverable_id: deliverable.id,
    version_no: (versions.at(-1)?.version_no ?? 0) + 1,
    content,
    file_refs: fileRefs.map((f) => ({ ...f, scan_status: scanStatus })),
    external_link: externalLink,
    submitted_by: userId,
    submitted_at: nowIso(),
    scan_status: scanStatus,
    is_locked: false,
  };
  db.submissionVersions.push(version);

  if (scanStatus === "infected") {
    // A quarantined file does not start the clock and does not move the
    // deliverable forward: the creator has to replace it.
    setOwner(deliverable, "changes_requested", userId);
    audit(db, "submission.quarantined", "submission_version", version.id);
    return { version, quarantined: true };
  }

  setOwner(deliverable, "submitted", userId);
  closeTasksFor(db, deliverable.id, "Submitted");

  const { campaign } = campaignForDeliverable(db, deliverable);
  if (startsClock(scanStatus)) {
    // The first stage's clock starts now; the brand's starts only on release.
    startSlaClock(db, deliverable, version.id, "puzzle_media");
  }

  notify(
    db,
    "usr_admin",
    "task_due",
    `New ${deliverable.type} to review`,
    `${campaign.name} — version ${version.version_no}`,
    `/admin/review/${version.id}`,
  );
  audit(db, "submission.created", "submission_version", version.id);

  return { version, quarantined: false };
});

route("GET", "/submissions/:id/versions", ({ db, params }) => {
  const version = must(
    db.submissionVersions.find((v) => v.id === params.id),
    "Submission",
  );
  return versionsOf(db, version.deliverable_id);
});

/* ── review ─────────────────────────────────────────────────────────── */

route("POST", "/submissions/:id/review", ({ db, params, body }) => {
  const reviewerId = currentUserId(db);
  const version = must(
    db.submissionVersions.find((v) => v.id === params.id),
    "Submission",
  );
  const deliverable = deliverableOf(db, version.deliverable_id);
  const { assignment, campaign } = campaignForDeliverable(db, deliverable);

  const input = {
    stage: (body.stage ?? "puzzle_media") as Review["stage"],
    decision: body.decision as Review["decision"],
    feedback: String(body.feedback ?? ""),
    reasonCode: (body.reasonCode ?? null) as Review["reason_code"],
    internalNote: (body.internalNote ?? null) as string | null,
    endsParticipation: Boolean(body.endsParticipation),
  };

  const validation = validateDecision(input);
  if (!validation.valid) {
    throw new ApiError("validation", "Check the decision details.", {
      fields: validation.errors as Record<string, string>,
    });
  }

  const priorReviews = db.reviews.filter((r) => r.submission_version_id === version.id);
  const versions = versionsOf(db, deliverable.id);
  const outcome = applyDecision(campaign, deliverable, versions, priorReviews, input);

  const review: Review = {
    id: newId("rev"),
    submission_version_id: version.id,
    reviewer_id: reviewerId,
    stage: input.stage,
    decision: input.decision,
    feedback: input.feedback,
    reason_code: input.reasonCode,
    internal_note: input.internalNote,
    ends_participation: outcome.endsParticipation,
    decided_at: nowIso(),
  };
  db.reviews.push(review);

  pauseSlaClocks(db, deliverable.id);

  const creatorId = assignment.creator_id;
  setOwner(deliverable, outcome.deliverableStatus, creatorId);

  if (outcome.releasedToNextStage && outcome.nextStage) {
    // D4: the brand's clock starts only when Puzzle Media releases to them.
    startSlaClock(db, deliverable, version.id, outcome.nextStage);
    deliverable.current_owner_kind = "brand";
    deliverable.current_owner_id = null;
  }

  if (outcome.deliverableStatus === "approved") {
    version.is_locked = true;
    closeTasksFor(db, deliverable.id, "Approved");

    // Approval of a script unlocks the linked video.
    const unlocked = db.deliverables.find(
      (d) => d.blocked_by_deliverable_id === deliverable.id,
    );
    if (unlocked && unlocked.status === "blocked") {
      setOwner(unlocked, "in_production", creatorId);
      openTask(db, creatorId, unlocked.type === "video" ? "submit_video" : "submit_script", {
        campaignId: campaign.id,
        deliverableId: unlocked.id,
        dueAt: unlocked.due_at,
        action: `Upload your video for ${campaign.name}`,
        deepLink: `/deliverables/${unlocked.id}`,
      });
    }

    if (deliverable.type === "video") {
      const livePostDeliverable = db.deliverables.find(
        (d) => d.assignment_id === assignment.id && d.type === "live_post",
      );
      if (livePostDeliverable) {
        setOwner(livePostDeliverable, "not_started", creatorId);
        openTask(db, creatorId, "publish_post", {
          campaignId: campaign.id,
          deliverableId: livePostDeliverable.id,
          dueAt: livePostDeliverable.due_at,
          action: `Publish and add your link for ${campaign.name}`,
          deepLink: `/deliverables/${livePostDeliverable.id}`,
        });
      }
    }

    notify(
      db,
      creatorId,
      "review_decision",
      `Your ${deliverable.type} was approved`,
      campaign.name,
      `/deliverables/${deliverable.id}`,
    );
  } else if (outcome.deliverableStatus === "changes_requested") {
    closeTasksFor(db, deliverable.id, "Changes requested");
    openTask(db, creatorId, deliverable.type === "video" ? "revise_video" : "revise_script", {
      campaignId: campaign.id,
      deliverableId: deliverable.id,
      dueAt: deliverable.due_at,
      action: `Revise your ${deliverable.type} for ${campaign.name}`,
      deepLink: `/deliverables/${deliverable.id}`,
    });
    notify(
      db,
      creatorId,
      "review_decision",
      `Changes requested on your ${deliverable.type}`,
      input.feedback.slice(0, 120),
      `/deliverables/${deliverable.id}`,
    );
  } else if (outcome.deliverableStatus === "rejected") {
    closeTasksFor(db, deliverable.id, "Rejected");
    if (outcome.endsParticipation) {
      assignment.participation_status = "removed";
      for (const t of db.tasks) {
        if (t.campaign_id === campaign.id && t.status === "open") {
          t.status = "cancelled";
          t.closed_at = nowIso();
          t.closed_reason = "Participation ended";
        }
      }
      audit(db, "assignment.removed", "campaign_assignment", assignment.id, input.feedback);
    }
    notify(
      db,
      creatorId,
      "review_decision",
      `Your ${deliverable.type} was rejected`,
      input.feedback.slice(0, 120),
      `/deliverables/${deliverable.id}`,
    );
  }

  audit(db, `review.${input.decision}`, "review", review.id, input.feedback);
  return { review, outcome };
});

/** Super admin grants another round past the cap (F-SUB-12). */
route("POST", "/deliverables/:id/grant-round", ({ db, params, body }) => {
  const deliverable = deliverableOf(db, params.id);
  const reason = String(body.reason ?? "");
  if (reason.trim().length < 5) {
    throw new ApiError("validation", "Give a reason for granting another round.", {
      fields: { reason: "Give a short reason." },
    });
  }
  deliverable.extra_rounds_granted += 1;
  const { assignment } = campaignForDeliverable(db, deliverable);
  setOwner(deliverable, "changes_requested", assignment.creator_id);
  audit(db, "deliverable.round_granted", "deliverable", deliverable.id, reason);
  return deliverable;
});

/* ── live post and metrics ──────────────────────────────────────────── */

const ALLOWED_POST_HOSTS = ["instagram.com", "youtube.com", "youtu.be", "linkedin.com"];

route("POST", "/deliverables/:id/live-post", ({ db, params, body }) => {
  const userId = currentUserId(db);
  const deliverable = deliverableOf(db, params.id);
  const url = String(body.url ?? "");
  const publishedAt = String(body.publishedAt ?? "");

  let host: string;
  try {
    host = new URL(url).hostname.replace(/^www\./, "");
  } catch {
    throw new ApiError("validation", "That does not look like a link.", {
      fields: { url: "Paste the full link to your post." },
    });
  }
  if (!ALLOWED_POST_HOSTS.some((h) => host === h || host.endsWith(`.${h}`))) {
    throw new ApiError("validation", "Link that post from a supported platform.", {
      fields: { url: "We accept Instagram, YouTube and LinkedIn links." },
    });
  }
  if (!publishedAt) {
    throw new ApiError("validation", "Tell us when you posted it.", {
      fields: { publishedAt: "Pick the date and time you published." },
    });
  }

  const livePost = {
    id: newId("lvp"),
    deliverable_id: deliverable.id,
    url,
    platform: (host.includes("youtu") ? "youtube" : host.includes("linkedin") ? "linkedin" : "instagram") as
      | "instagram"
      | "youtube"
      | "linkedin",
    post_id: null,
    published_at: new Date(publishedAt).toISOString(),
    // Screenshot is optional by product decision; URL and time are required.
    proof_ref: (body.proof ?? null) as never,
    verified_by: null,
    verified_at: null,
  };
  db.livePosts.push(livePost);

  setOwner(deliverable, "live_link_submitted", userId);
  closeTasksFor(db, deliverable.id, "Link submitted");
  audit(db, "live_post.submitted", "live_post", livePost.id);

  return livePost;
});

route("POST", "/live-posts/:id/verify", ({ db, params }) => {
  const adminId = currentUserId(db);
  const livePost = must(
    db.livePosts.find((l) => l.id === params.id),
    "Live post",
  );
  livePost.verified_by = adminId;
  livePost.verified_at = nowIso();

  const deliverable = deliverableOf(db, livePost.deliverable_id);
  setOwner(deliverable, "link_verified", null);

  const { assignment } = campaignForDeliverable(db, deliverable);
  const earning = db.earnings.find((e) => e.assignment_id === assignment.id);
  if (earning) {
    earning.gates_met = Array.from(new Set([...earning.gates_met, "link_verified"]));
    earning.status = "payment_pending";
    earning.updated_at = nowIso();
    earning.updated_by = adminId;
  }

  audit(db, "live_post.verified", "live_post", livePost.id);
  return livePost;
});

route("POST", "/live-posts/:id/metrics", ({ db, params, body }) => {
  const userId = currentUserId(db);
  const livePost = must(
    db.livePosts.find((l) => l.id === params.id),
    "Live post",
  );
  const entries = (body.metrics ?? {}) as Record<string, number>;
  const window = String(body.window ?? "7d") as "24h" | "7d" | "30d";

  const created = Object.entries(entries)
    .filter(([, value]) => Number.isFinite(value))
    .map(([metricType, value]) => {
      const snapshot = {
        id: newId("mtr"),
        live_post_id: livePost.id,
        metric_type: metricType as never,
        window,
        value: Number(value),
        // Provenance is never inferred: the creator entered this.
        source: "creator_submitted" as const,
        captured_at: nowIso(),
        captured_by: userId,
        verification_status: "unverified" as const,
        raw_ref: null,
        superseded_by: null,
      };
      db.metricSnapshots.push(snapshot);
      return snapshot;
    });

  const deliverable = deliverableOf(db, livePost.deliverable_id);
  closeTasksFor(db, deliverable.id, "Results added");
  audit(db, "metrics.submitted", "live_post", livePost.id);

  return created;
});

route("POST", "/metrics/:id/verify", ({ db, params, body }) => {
  const adminId = currentUserId(db);
  const original = must(
    db.metricSnapshots.find((m) => m.id === params.id),
    "Metric",
  );
  const corrected = body.value == null ? null : Number(body.value);
  const reason = String(body.reason ?? "");

  if (corrected !== null && corrected !== original.value) {
    if (reason.trim().length < 5) {
      throw new ApiError("validation", "Give a reason for correcting this number.", {
        fields: { reason: "Say why the number changed." },
      });
    }
    // F-REP-03: a correction inserts a new snapshot; the original is retained.
    const replacement = {
      ...original,
      id: newId("mtr"),
      value: corrected,
      source: "admin_verified" as const,
      captured_at: nowIso(),
      captured_by: adminId,
      verification_status: "corrected" as const,
      superseded_by: null,
    };
    original.superseded_by = replacement.id;
    db.metricSnapshots.push(replacement);
    audit(db, "metrics.corrected", "metric_snapshot", replacement.id, reason);
    return replacement;
  }

  original.verification_status = "verified";
  audit(db, "metrics.verified", "metric_snapshot", original.id);
  return original;
});

/* ── tasks, notifications, earnings ─────────────────────────────────── */

route("GET", "/tasks", ({ db }) => {
  const userId = currentUserId(db);
  return db.tasks.filter((t) => t.user_id === userId);
});

route("GET", "/notifications", ({ db }) => {
  const userId = currentUserId(db);
  return db.notifications.filter((n) => n.user_id === userId);
});

route("POST", "/notifications/:id/read", ({ db, params }) => {
  const notification = must(
    db.notifications.find((n) => n.id === params.id),
    "Notification",
  );
  notification.read_at ??= nowIso();
  return notification;
});

route("POST", "/notifications/read-all", ({ db }) => {
  const userId = currentUserId(db);
  for (const n of db.notifications) {
    if (n.user_id === userId) n.read_at ??= nowIso();
  }
  return { ok: true };
});

route("GET", "/earnings", ({ db }) => {
  const userId = currentUserId(db);
  const assignments = db.assignments.filter((a) => a.creator_id === userId);
  const items = assignments
    .map((assignment) => {
      const earning = db.earnings.find((e) => e.assignment_id === assignment.id) ?? null;
      const campaign = db.campaigns.find((c) => c.id === assignment.campaign_id)!;
      const brand = db.brands.find((b) => b.id === campaign.brand_id)!;
      return { assignment, earning, campaign, brand };
    })
    .filter((row) => row.assignment.visible_to_creator);

  return { items };
});

/* ── performance ────────────────────────────────────────────────────── */

route("GET", "/performance", ({ db }) => {
  const userId = currentUserId(db);
  const assignments = db.assignments.filter((a) => a.creator_id === userId);
  const assignmentIds = new Set(assignments.map((a) => a.id));
  const deliverables = db.deliverables.filter((d) => assignmentIds.has(d.assignment_id));
  const deliverableIds = new Set(deliverables.map((d) => d.id));
  const livePosts = db.livePosts.filter((l) => deliverableIds.has(l.deliverable_id));

  const items = livePosts.map((livePost) => {
    const deliverable = deliverables.find((d) => d.id === livePost.deliverable_id)!;
    const assignment = assignments.find((a) => a.id === deliverable.assignment_id)!;
    const campaign = db.campaigns.find((c) => c.id === assignment.campaign_id)!;
    const brand = db.brands.find((b) => b.id === campaign.brand_id)!;
    const snapshots = db.metricSnapshots.filter(
      (m) => m.live_post_id === livePost.id && !m.superseded_by,
    );
    return { livePost, campaign, brand, snapshots };
  });

  return { items };
});

/* ── events ─────────────────────────────────────────────────────────── */

route("GET", "/events", ({ db }) => {
  const userId = currentUserId(db);
  const items = db.events.map((event) => ({
    event,
    speaker: db.speakers.find((s) => s.id === event.speaker_id) ?? null,
    rsvp: db.rsvps.find((r) => r.event_id === event.id && r.user_id === userId) ?? null,
    goingCount: db.rsvps.filter((r) => r.event_id === event.id && r.state === "going").length,
  }));
  return { items };
});

route("POST", "/events/:id/rsvp", ({ db, params }) => {
  const userId = currentUserId(db);
  const event = must(
    db.events.find((e) => e.id === params.id),
    "Event",
  );
  const existing = db.rsvps.find((r) => r.event_id === event.id && r.user_id === userId);
  const going = db.rsvps.filter((r) => r.event_id === event.id && r.state === "going").length;

  if (existing) {
    existing.state = existing.state === "going" ? "cancelled" : "going";
    return existing;
  }

  // Capacity full sends the creator to the waitlist rather than refusing.
  const rsvp = {
    id: newId("rsv"),
    event_id: event.id,
    user_id: userId,
    state: going >= event.capacity ? ("waitlisted" as const) : ("going" as const),
    created_at: nowIso(),
    checked_in_at: null,
    completed_at: null,
  };
  db.rsvps.push(rsvp);
  return rsvp;
});

/* ── reviewer ───────────────────────────────────────────────────────── */

route("GET", "/reviewer/queue", ({ db }) => {
  const userId = currentUserId(db);
  const user = must(
    db.users.find((u) => u.id === userId),
    "User",
  );
  const stage: ReviewStage =
    user.role === "brand_reviewer" || user.role === "brand_admin"
      ? "brand"
      : "puzzle_media";

  const scopedCampaignIds = new Set(
    db.campaignReviewers.filter((r) => r.user_id === userId).map((r) => r.campaign_id),
  );

  const items = db.deliverables
    .filter((d) => d.status === "submitted" || d.status === "under_review")
    .map((deliverable) => {
      const { assignment, campaign } = campaignForDeliverable(db, deliverable);
      const versions = versionsOf(db, deliverable.id);
      const latest = versions.at(-1);
      if (!latest) return null;

      const reviews = db.reviews.filter((r) => r.submission_version_id === latest.id);
      const brand = db.brands.find((b) => b.id === campaign.brand_id)!;
      const creator = db.creatorProfiles.find((p) => p.user_id === assignment.creator_id)!;
      const clock =
        db.slaClocks
          .filter((c) => c.submission_version_id === latest.id && c.stage === stage)
          .at(-1) ?? null;

      return {
        deliverable,
        campaign,
        brand,
        creator,
        version: latest,
        versions,
        reviews,
        slaClock: clock,
        stage,
        inScope: scopedCampaignIds.has(campaign.id),
      };
    })
    .filter((x): x is NonNullable<typeof x> => x !== null)
    // A brand reviewer never sees work Puzzle Media has not released.
    .filter((x) => x.inScope)
    .filter((x) => {
      if (stage === "puzzle_media") return true;
      return x.reviews.some((r) => r.stage === "puzzle_media" && r.decision === "approve");
    })
    .filter((x) => !x.reviews.some((r) => r.stage === stage && r.decision === "approve"));

  return { items, stage };
});

route("GET", "/reviewer/submissions/:id", ({ db, params }) => {
  const userId = currentUserId(db);
  const user = must(
    db.users.find((u) => u.id === userId),
    "User",
  );
  const stage: ReviewStage =
    user.role === "brand_reviewer" || user.role === "brand_admin"
      ? "brand"
      : "puzzle_media";

  const version = must(
    db.submissionVersions.find((v) => v.id === params.id),
    "Submission",
  );
  const deliverable = deliverableOf(db, version.deliverable_id);
  const { assignment, campaign } = campaignForDeliverable(db, deliverable);
  const versions = versionsOf(db, deliverable.id);
  const versionIds = new Set(versions.map((v) => v.id));
  const reviews = db.reviews.filter((r) => versionIds.has(r.submission_version_id));

  const releasedToBrand = db.reviews.some(
    (r) =>
      r.submission_version_id === version.id &&
      r.stage === "puzzle_media" &&
      r.decision === "approve",
  );
  if (stage === "brand" && !releasedToBrand) {
    // Not 403: the brand should not learn this submission exists yet.
    throw new ApiError("not_found", "Submission not found");
  }

  return {
    version,
    versions,
    deliverable,
    assignment,
    campaign,
    brand: db.brands.find((b) => b.id === campaign.brand_id)!,
    creator: db.creatorProfiles.find((p) => p.user_id === assignment.creator_id)!,
    socialAccounts: db.socialAccounts.filter(
      (s) => s.creator_id === db.creatorProfiles.find((p) => p.user_id === assignment.creator_id)?.id,
    ),
    brief: db.briefVersions
      .filter((b) => b.campaign_id === campaign.id)
      .sort((a, b) => b.version - a.version)[0],
    reviews,
    slaClocks: db.slaClocks.filter((c) => c.deliverable_id === deliverable.id),
    stage,
    budget: draftBudget(deliverable, versions),
  };
});

/* ── admin ──────────────────────────────────────────────────────────── */

route("GET", "/admin/overview", ({ db }) => {
  const pendingReview = db.deliverables.filter(
    (d) => d.status === "submitted" || d.status === "under_review",
  ).length;
  const unverifiedLinks = db.livePosts.filter((l) => !l.verified_at).length;
  const openBreaches = db.slaClocks.filter(
    (c) => !c.paused_at && new Date(c.due_at) < new Date(),
  ).length;
  const pendingProfiles = db.creatorProfiles.filter(
    (p) => p.verification_status === "pending_review",
  ).length;
  const metricsOutstanding = db.livePosts.filter(
    (l) => !db.metricSnapshots.some((m) => m.live_post_id === l.id && m.window === "7d"),
  ).length;

  return {
    pendingReview,
    unverifiedLinks,
    openBreaches,
    pendingProfiles,
    metricsOutstanding,
    creators: db.creatorProfiles.length,
    campaigns: db.campaigns.length,
    brands: db.brands.length,
  };
});

route("GET", "/admin/creators", ({ db }) => {
  const items = db.creatorProfiles.map((profile) => ({
    profile,
    user: db.users.find((u) => u.id === profile.user_id)!,
    socialAccounts: db.socialAccounts.filter((s) => s.creator_id === profile.id),
    assignments: db.assignments.filter((a) => a.creator_id === profile.user_id).length,
  }));
  return { items };
});

route("GET", "/admin/queue/sla", ({ db }) => {
  const items = db.slaClocks
    .map((clock) => {
      const deliverable = db.deliverables.find((d) => d.id === clock.deliverable_id);
      if (!deliverable) return null;
      const { assignment, campaign } = campaignForDeliverable(db, deliverable);
      return {
        clock,
        deliverable,
        campaign,
        creator: db.creatorProfiles.find((p) => p.user_id === assignment.creator_id)!,
      };
    })
    .filter((x): x is NonNullable<typeof x> => x !== null);
  return { items };
});

route("GET", "/admin/live-posts", ({ db }) => {
  const items = db.livePosts.map((livePost) => {
    const deliverable = db.deliverables.find((d) => d.id === livePost.deliverable_id)!;
    const { assignment, campaign } = campaignForDeliverable(db, deliverable);
    return {
      livePost,
      campaign,
      creator: db.creatorProfiles.find((p) => p.user_id === assignment.creator_id)!,
    };
  });
  return { items };
});

route("GET", "/admin/earnings", ({ db }) => {
  const items = db.earnings.map((earning) => {
    const assignment = db.assignments.find((a) => a.id === earning.assignment_id)!;
    const campaign = db.campaigns.find((c) => c.id === assignment.campaign_id)!;
    return {
      earning,
      assignment,
      campaign,
      brand: db.brands.find((b) => b.id === campaign.brand_id)!,
      creator: db.creatorProfiles.find((p) => p.user_id === assignment.creator_id)!,
    };
  });
  return { items };
});

route("GET", "/admin/audit", ({ db }) => ({ items: db.auditLog.slice(0, 200) }));

/* ── the transport ──────────────────────────────────────────────────── */

export const mockTransport: Transport = async <T,>(
  req: ApiRequest,
): Promise<ApiResponse<T>> => {
  store.hydrate();

  const scenarios = getScenarios();
  const requestId = newId("req");

  await delayFor(classify(req.method, req.path));
  if (scenarios.slowNetwork) await new Promise((r) => setTimeout(r, 2000));

  if (req.signal?.aborted) throw new ApiError("network", "Request cancelled");

  if (scenarios.networkError) {
    throw new ApiError("network", "Simulated network failure", { requestId });
  }

  // Idempotent replay: a repeated key returns the first response rather than
  // creating a second record. This is what makes double-tap safe on 4G.
  if (req.idempotencyKey && idempotencyCache.has(req.idempotencyKey)) {
    return { data: idempotencyCache.get(req.idempotencyKey) as T, requestId };
  }
  if (scenarios.conflict && req.method !== "GET") {
    throw new ApiError("conflict", "Simulated conflict", { requestId });
  }

  const match = routes.find(
    (r) => r.method === req.method && r.pattern.test(req.path),
  );
  if (!match) {
    throw new ApiError("not_found", `No handler for ${req.method} ${req.path}`, {
      requestId,
    });
  }

  const captured = match.pattern.exec(req.path)!.slice(1);
  const params = Object.fromEntries(match.keys.map((k, i) => [k, captured[i]]));
  const body = (req.body ?? {}) as Record<string, unknown>;

  if (scenarios.validationError && req.method !== "GET") {
    throw new ApiError("validation", "Simulated validation failure", {
      fields: { form: "This is a simulated error from the scenario panel." },
      requestId,
    });
  }

  const run = (db: Database) =>
    match.handler({ db, params, query: req.query ?? {}, body });

  const data = match.mutates ? store.write(run) : run(store.read());

  if (req.idempotencyKey) idempotencyCache.set(req.idempotencyKey, data);

  // Structured-clone the response so callers cannot mutate store state by
  // holding onto a reference — the same isolation a real network gives.
  return { data: JSON.parse(JSON.stringify(data)) as T, requestId };
};
